import Head from "next/head";
import { Inter } from "next/font/google";
import AddName from "@/components/addname/AddName";
import Display from "@/components/display/Display";
import Search from "@/components/search/Search";
import { Button } from "@mui/material";
import { useRouter } from "next/router";
import MyForm from "@/components/MyForm/MyForm";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ display: "flex", justifyContent: "center" }}>
        <div>
          <AddName />
          <Display />
          <Search />
          <div>
            <Button onClick={() => router.push("/hello")}>Load Data</Button>
          </div>
          <div>
            <MyForm />
          </div>
        </div>
      </div>
    </>
  );
}
